---

- name: download
  shell: "wget https://download.elasticsearch.org/kibana/kibana/kibana-4.0.1-linux-x64.tar.gz -O - | tar zxf - -C /opt"
  args:
    creates: /opt/kibana

- name: symlink
  file:
    src=/opt/kibana-4.0.1-linux-x64/
    dest=/opt/kibana
    state=link

- name: init script
  shell: "wget https://gist.githubusercontent.com/thisismitch/8b15ac909aed214ad04a/raw/bce61d85643c2dcdfbc2728c55a41dab444dca20/kibana4 -O /etc/init.d/kibana"
  args:
    creates: /etc/init.d/kibana

- name: init script permissions
  file:
    path=/etc/init.d/kibana
    mode=0755

- name: service
  service:
    name=kibana
    state=started
    enabled=yes
