---

- name: apt-key
  apt_key:
    url="http://packages.elasticsearch.org/GPG-KEY-elasticsearch"
    state=present

- name: repository
  apt_repository:
    repo="deb http://packages.elasticsearch.org/elasticsearch/1.5/debian stable main"
    state=present

- name: package
  apt:
    name=elasticsearch
    state=present
  notify: restart elasticsearch

- name: config
  copy:
    src=elasticsearch/elasticsearch.yml
    dest=/etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch

- name: nginx config
  copy:
    src=nginx/elasticsearch
    dest=/etc/nginx/sites-available/elasticsearch
  notify: reload nginx

- name: nginx config symlink
  file:
    src=/etc/nginx/sites-available/elasticsearch
    dest=/etc/nginx/sites-enabled/elasticsearch
    state=link
  notify: reload nginx

- name: dnsmasq config
  copy:
    src=dnsmasq/elasticsearch
    dest=/etc/NetworkManager/dnsmasq.d/elasticsearch
  notify: restart network-manager

- name: head plugin
  shell: "/usr/share/elasticsearch/bin/plugin --install mobz/elasticsearch-head"
  args:
    creates: /usr/share/elasticsearch/plugins/head/
  notify: restart elasticsearch

- name: HQ plugin
  shell: "/usr/share/elasticsearch/bin/plugin --install royrusso/elasticsearch-HQ"
  args:
    creates: /usr/share/elasticsearch/plugins/HQ/
  notify: restart elasticsearch

- name: service
  service:
    name=elasticsearch
    enabled=yes
    state=started
